import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type Lang = 'fr' | 'en' | 'ar';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {

  private static readonly LANGS: Lang[] = ['fr', 'en', 'ar'];

  private currentLang = new BehaviorSubject<Lang>(
    (localStorage.getItem('lang') as Lang) || 'fr'
  );

  currentLang$ = this.currentLang.asObservable();

  constructor() {
    const lang = this.getLanguage();
    this.applyLanguageAttributes(lang);
  }

  getLanguage(): Lang {
    return this.currentLang.getValue();
  }

  setLanguage(lang: Lang) {
    this.currentLang.next(lang);
    localStorage.setItem('lang', lang);
    this.applyLanguageAttributes(lang);
  }

  private applyLanguageAttributes(lang: Lang) {
    document.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }

  /** Cycle through fr â†’ en â†’ ar â†’ fr */
  toggleLanguage() {
    const idx = LanguageService.LANGS.indexOf(this.getLanguage());
    const next = LanguageService.LANGS[(idx + 1) % LanguageService.LANGS.length];
    this.setLanguage(next);
  }

  /** Get all supported languages for dropdown */
  getAvailableLanguages(): { code: Lang; label: string; flag: string }[] {
    return [
      { code: 'fr', label: 'Francais', flag: 'FR' },
      { code: 'en', label: 'English',  flag: 'EN' },
      { code: 'ar', label: 'العربية',  flag: 'AR' }
    ];
  }

  // ============================================
  // TRADUCTIONS COMPLÃˆTES â€” FR / EN / AR
  // ============================================
  t(key: string): string {
    const cleanTranslations: Record<Lang, Record<string, string>> = {
      fr: {
        'app.title': 'Assistant Administratif',
        'app.subtitle': 'Portail Administratif',
        'app.status': 'En ligne',
        'app.admin': 'Tableau de bord',
        'app.logout': 'Deconnexion',
        'app.newchat': 'Nouvelle conversation',
        'app.history': 'Conversations recentes',
        'app.noconv': 'Aucune conversation',
        'app.admin_role': 'Administrateur',
        'app.user_role': 'Utilisateur',
        'app.profile': 'Mon profil',
        'app.settings': 'Parametres',
        'app.language': 'Langue',
        'app.notifications': 'Notifications',

        'login.title': 'Connectez-vous a votre compte',
        'login.subtitle': 'Portail Administratif Intelligent',
        'login.username': "Nom d'utilisateur",
        'login.username_placeholder': 'votre_identifiant',
        'login.password': 'Mot de passe',
        'login.forgot': 'Mot de passe oublie ?',
        'login.remember': 'Rester connecte',
        'login.btn': 'Se connecter',
        'login.error': "Nom d'utilisateur ou mot de passe incorrect",
        'login.empty_fields': 'Veuillez remplir tous les champs',
        'login.no_account': 'Pas encore membre ?',
        'login.register': 'Creer un compte',
        'login.or': 'OU',
        'login.footer': '© 2026 Faculte des Sciences - Projet PFE FASTO',

        'register.title': 'Creer un nouveau compte',
        'register.choose_role': 'Choisissez votre role',
        'register.student': 'Etudiant',
        'register.professor': 'Professeur',
        'register.student_id': 'Identifiant etudiant',
        'register.prof_id': 'Identifiant professeur',
        'register.id_placeholder': "Identifiant fourni par l'administration",
        'register.personal_info': 'Informations personnelles',
        'register.first_name': 'Prenom',
        'register.last_name': 'Nom',
        'register.email': 'Email',
        'register.cin': 'Numero CIN',
        'register.phone': 'Telephone',
        'register.address': 'Adresse',
        'register.gender': 'Genre',
        'register.male': 'Homme',
        'register.female': 'Femme',
        'register.academic_info': 'Informations academiques',
        'register.field_of_study': 'Filiere',
        'register.bac_type': 'Type de baccalaureat',
        'register.scholarship': 'Boursier',
        'register.department': 'Departement',
        'register.account_info': 'Informations du compte',
        'register.username': "Nom d'utilisateur",
        'register.password': 'Mot de passe',
        'register.confirm_password': 'Confirmer le mot de passe',
        'register.accept_terms': "J'accepte les conditions d'utilisation",
        'register.btn': "S'inscrire",
        'register.error_match': 'Les mots de passe ne correspondent pas',
        'register.error_length': 'Le mot de passe doit contenir au moins 6 caracteres',
        'register.success': 'Compte cree avec succes ! Redirection...',
        'register.error_used': 'Nom utilisateur ou email deja utilise',
        'register.already_account': 'Vous avez deja un compte ?',
        'register.login': 'Se connecter',
        'register.yes': 'Oui',
        'register.no': 'Non',

        'chat.placeholder': 'Posez votre question a FASTO...',
        'chat.welcome_title': "Comment puis-je vous aider aujourd'hui ?",
        'chat.welcome_desc': 'Je peux vous aider pour les horaires, les documents administratifs et vos notes.',
        'chat.welcome': 'Bonjour ! Je suis votre assistant administratif intelligent.',
        'chat.new_assistant': 'Nouvel assistant',
        'chat.admin_section': 'Administration',
        'chat.dashboard': 'Tableau de bord',
        'chat.faculty_mgmt': 'Gestion des filieres',
        'chat.rooms_mgmt': 'Gestion des salles',
        'chat.subjects_mgmt': 'Gestion des matieres',
        'chat.planning': 'Planning',
        'chat.prof_section': 'Espace professeur',
        'chat.my_planning': 'Mon planning',
        'chat.my_subjects': 'Mes matieres',
        'chat.documents': 'Documents',
        'chat.student_section': 'Espace etudiant',
        'chat.timetable': 'Emploi du temps',
        'chat.my_documents': 'Mes documents',
        'chat.recent': 'Recent',
        'chat.assistant_title': 'Assistant FASTO',
        'chat.assistant_subtitle': 'Assistant IA de la faculte',
        'chat.sources': 'Sources :',
        'chat.copy': 'Copier',
        'chat.fasto_ai': 'FASTO AI',

        'suggestion.timetable': 'Mon emploi du temps',
        'suggestion.certificate': 'Attestation de scolarite',
        'suggestion.grades': 'Mon releve de notes',
        'suggestion.scholarships': 'Bourses disponibles',
        'suggestion.programs': 'Filieres proposees',
        'suggestion.registration': "Comment s'inscrire",
        'suggestion.calendar': 'Calendrier academique',
        'suggestion.rules': 'Reglement interieur',

        'form.title': 'Generateur de documents',
        'form.type': 'Type de document',
        'form.name': 'Nom complet',
        'form.name_placeholder': 'Ex: Ahmed Ben Salah',
        'form.format': 'Format',
        'form.generate': 'Generer le document',
        'form.generating': 'Generation en cours...',
        'form.cancel': 'Annuler',
        'form.academic_year': 'Annee universitaire',
        'form.academic_year_placeholder': 'Ex: 2024/2025',
        'form.address': 'Adresse complete',
        'form.company': 'Entreprise de stage',
        'form.duration': 'Duree du stage',
        'form.duration_placeholder': 'Ex: 3 mois',
        'form.recipient': 'Destinataire / objet',
        'form.additional': 'Informations supplementaires',
        'form.additional_placeholder': 'Ajoutez des precisions si necessaire...',

        'doc.attest_travail': 'Attestation de travail',
        'doc.attest_scolarite': 'Attestation de scolarite',
        'doc.attest_residence': 'Attestation de residence',
        'doc.generated': 'Votre document a ete genere.',
        'doc.download': 'Telecharger le document',
        'doc.error': 'Erreur lors de la generation du document.',
        'doc.name_required': 'Veuillez entrer votre nom complet',
        'doc.certificat_scolarite': 'Certificat de scolarite',
        'doc.releve_notes': 'Releve de notes',
        'doc.attest_stage': 'Attestation de stage',
        'doc.attest_presence': 'Attestation de presence',
        'doc.attest_residence_label': 'Attestation de residence',
        'doc.copie_conforme': 'Copie conforme',
        'doc.declaration_honneur': "Declaration sur l'honneur",
        'doc.lettre_motivation': 'Lettre de motivation',
        'doc.lettre_demande': 'Lettre de demande',
        'doc.lettre_reclamation': 'Lettre de reclamation',
        'doc.group_academic': 'Academique',
        'doc.group_admin': 'Administratif',
        'doc.group_letters': 'Lettres',

        'role.admin': 'Administrateur',
        'role.professor': 'Professeur',
        'role.student': 'Etudiant',

        'page.admin': 'Tableau de Bord Admin',
        'page.chat': 'Assistant IA',
        'page.login': 'Connexion',
        'page.register': 'Inscription',
        'page.default': 'Portail FASTO'
      },
      en: {
        'app.title': 'Administrative Assistant',
        'app.subtitle': 'Administrative Portal',
        'app.status': 'Online',
        'app.admin': 'Dashboard',
        'app.logout': 'Sign out',
        'app.newchat': 'New conversation',
        'app.history': 'Recent conversations',
        'app.noconv': 'No conversations',
        'app.admin_role': 'Administrator',
        'app.user_role': 'User',
        'app.profile': 'My profile',
        'app.settings': 'Settings',
        'app.language': 'Language',
        'app.notifications': 'Notifications',

        'login.title': 'Sign in to your account',
        'login.subtitle': 'Smart Administrative Portal',
        'login.username': 'Username',
        'login.username_placeholder': 'your_username',
        'login.password': 'Password',
        'login.forgot': 'Forgot password?',
        'login.remember': 'Keep me signed in',
        'login.btn': 'Sign in',
        'login.error': 'Incorrect username or password',
        'login.empty_fields': 'Please fill in all fields',
        'login.no_account': 'Not a member yet?',
        'login.register': 'Create an account',
        'login.or': 'OR',
        'login.footer': '© 2026 Faculty of Sciences - FASTO graduation project',

        'register.title': 'Create a new account',
        'register.choose_role': 'Choose your role',
        'register.student': 'Student',
        'register.professor': 'Professor',
        'register.student_id': 'Student identifier',
        'register.prof_id': 'Professor identifier',
        'register.id_placeholder': 'Identifier provided by the administration',
        'register.personal_info': 'Personal information',
        'register.first_name': 'First name',
        'register.last_name': 'Last name',
        'register.email': 'Email',
        'register.cin': 'National ID number',
        'register.phone': 'Phone',
        'register.address': 'Address',
        'register.gender': 'Gender',
        'register.male': 'Male',
        'register.female': 'Female',
        'register.academic_info': 'Academic information',
        'register.field_of_study': 'Program',
        'register.bac_type': 'Baccalaureate type',
        'register.scholarship': 'Scholarship holder',
        'register.department': 'Department',
        'register.account_info': 'Account information',
        'register.username': 'Username',
        'register.password': 'Password',
        'register.confirm_password': 'Confirm password',
        'register.accept_terms': 'I accept the terms of use',
        'register.btn': 'Register',
        'register.error_match': 'Passwords do not match',
        'register.error_length': 'Password must contain at least 6 characters',
        'register.success': 'Account created successfully! Redirecting...',
        'register.error_used': 'Username or email already used',
        'register.already_account': 'Already have an account?',
        'register.login': 'Sign in',
        'register.yes': 'Yes',
        'register.no': 'No',

        'chat.placeholder': 'Ask your question to FASTO...',
        'chat.welcome_title': 'How can I help you today?',
        'chat.welcome_desc': 'I can help you with schedules, administrative documents and grades.',
        'chat.welcome': 'Hello! I am your smart administrative assistant.',
        'chat.new_assistant': 'New assistant',
        'chat.admin_section': 'Administration',
        'chat.dashboard': 'Dashboard',
        'chat.faculty_mgmt': 'Program management',
        'chat.rooms_mgmt': 'Room management',
        'chat.subjects_mgmt': 'Subject management',
        'chat.planning': 'Schedule',
        'chat.prof_section': 'Professor area',
        'chat.my_planning': 'My schedule',
        'chat.my_subjects': 'My subjects',
        'chat.documents': 'Documents',
        'chat.student_section': 'Student area',
        'chat.timetable': 'Timetable',
        'chat.my_documents': 'My documents',
        'chat.recent': 'Recent',
        'chat.assistant_title': 'FASTO Assistant',
        'chat.assistant_subtitle': 'Faculty AI assistant',
        'chat.sources': 'Sources:',
        'chat.copy': 'Copy',
        'chat.fasto_ai': 'FASTO AI',

        'suggestion.timetable': 'My timetable',
        'suggestion.certificate': 'School certificate',
        'suggestion.grades': 'My transcript',
        'suggestion.scholarships': 'Available scholarships',
        'suggestion.programs': 'Available programs',
        'suggestion.registration': 'How to register',
        'suggestion.calendar': 'Academic calendar',
        'suggestion.rules': 'Internal regulations',

        'form.title': 'Document generator',
        'form.type': 'Document type',
        'form.name': 'Full name',
        'form.name_placeholder': 'Example: Ahmed Ben Salah',
        'form.format': 'Format',
        'form.generate': 'Generate document',
        'form.generating': 'Generating...',
        'form.cancel': 'Cancel',
        'form.academic_year': 'Academic year',
        'form.academic_year_placeholder': 'Example: 2024/2025',
        'form.address': 'Full address',
        'form.company': 'Internship company',
        'form.duration': 'Internship duration',
        'form.duration_placeholder': 'Example: 3 months',
        'form.recipient': 'Recipient / subject',
        'form.additional': 'Additional information',
        'form.additional_placeholder': 'Add details if needed...',

        'doc.attest_travail': 'Work certificate',
        'doc.attest_scolarite': 'School certificate',
        'doc.attest_residence': 'Residence certificate',
        'doc.generated': 'Your document has been generated.',
        'doc.download': 'Download document',
        'doc.error': 'Error while generating the document.',
        'doc.name_required': 'Please enter your full name',
        'doc.certificat_scolarite': 'Enrollment certificate',
        'doc.releve_notes': 'Transcript',
        'doc.attest_stage': 'Internship certificate',
        'doc.attest_presence': 'Attendance certificate',
        'doc.attest_residence_label': 'Residence certificate',
        'doc.copie_conforme': 'Certified copy',
        'doc.declaration_honneur': 'Statement of honor',
        'doc.lettre_motivation': 'Cover letter',
        'doc.lettre_demande': 'Request letter',
        'doc.lettre_reclamation': 'Complaint letter',
        'doc.group_academic': 'Academic',
        'doc.group_admin': 'Administrative',
        'doc.group_letters': 'Letters',

        'role.admin': 'Administrator',
        'role.professor': 'Professor',
        'role.student': 'Student',

        'page.admin': 'Admin Dashboard',
        'page.chat': 'AI Assistant',
        'page.login': 'Login',
        'page.register': 'Register',
        'page.default': 'FASTO Portal'
      },
      ar: {
        'app.title': 'المساعد الإداري',
        'app.subtitle': 'البوابة الإدارية',
        'app.status': 'متصل',
        'app.admin': 'لوحة التحكم',
        'app.logout': 'تسجيل الخروج',
        'app.newchat': 'محادثة جديدة',
        'app.history': 'المحادثات الأخيرة',
        'app.noconv': 'لا توجد محادثات',
        'app.admin_role': 'مدير',
        'app.user_role': 'مستخدم',
        'app.profile': 'ملفي الشخصي',
        'app.settings': 'الإعدادات',
        'app.language': 'اللغة',
        'app.notifications': 'الإشعارات',

        'login.title': 'سجل الدخول إلى حسابك',
        'login.subtitle': 'بوابة إدارية ذكية',
        'login.username': 'اسم المستخدم',
        'login.username_placeholder': 'اسم_المستخدم',
        'login.password': 'كلمة المرور',
        'login.forgot': 'هل نسيت كلمة المرور؟',
        'login.remember': 'ابق متصلا',
        'login.btn': 'تسجيل الدخول',
        'login.error': 'اسم المستخدم أو كلمة المرور غير صحيحة',
        'login.empty_fields': 'يرجى ملء جميع الحقول',
        'login.no_account': 'ليس لديك حساب بعد؟',
        'login.register': 'إنشاء حساب',
        'login.or': 'أو',
        'login.footer': '© 2026 كلية العلوم - مشروع تخرج FASTO',

        'register.title': 'إنشاء حساب جديد',
        'register.choose_role': 'اختر دورك',
        'register.student': 'طالب',
        'register.professor': 'أستاذ',
        'register.student_id': 'معرف الطالب',
        'register.prof_id': 'معرف الأستاذ',
        'register.id_placeholder': 'المعرف المقدم من الإدارة',
        'register.personal_info': 'المعلومات الشخصية',
        'register.first_name': 'الاسم',
        'register.last_name': 'اللقب',
        'register.email': 'البريد الإلكتروني',
        'register.cin': 'رقم بطاقة التعريف',
        'register.phone': 'الهاتف',
        'register.address': 'العنوان',
        'register.gender': 'الجنس',
        'register.male': 'ذكر',
        'register.female': 'أنثى',
        'register.academic_info': 'المعلومات الأكاديمية',
        'register.field_of_study': 'الاختصاص',
        'register.bac_type': 'نوع البكالوريا',
        'register.scholarship': 'منحة',
        'register.department': 'القسم',
        'register.account_info': 'معلومات الحساب',
        'register.username': 'اسم المستخدم',
        'register.password': 'كلمة المرور',
        'register.confirm_password': 'تأكيد كلمة المرور',
        'register.accept_terms': 'أوافق على شروط الاستخدام',
        'register.btn': 'تسجيل',
        'register.error_match': 'كلمتا المرور غير متطابقتين',
        'register.error_length': 'يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل',
        'register.success': 'تم إنشاء الحساب بنجاح! جار التحويل...',
        'register.error_used': 'اسم المستخدم أو البريد الإلكتروني مستعمل مسبقا',
        'register.already_account': 'لديك حساب بالفعل؟',
        'register.login': 'تسجيل الدخول',
        'register.yes': 'نعم',
        'register.no': 'لا',

        'chat.placeholder': 'اكتب سؤالك إلى FASTO...',
        'chat.welcome_title': 'كيف يمكنني مساعدتك اليوم؟',
        'chat.welcome_desc': 'أستطيع مساعدتك في الجداول والوثائق الإدارية والأعداد.',
        'chat.welcome': 'مرحبا! أنا مساعدك الإداري الذكي.',
        'chat.new_assistant': 'مساعد جديد',
        'chat.admin_section': 'الإدارة',
        'chat.dashboard': 'لوحة التحكم',
        'chat.faculty_mgmt': 'إدارة الاختصاصات',
        'chat.rooms_mgmt': 'إدارة القاعات',
        'chat.subjects_mgmt': 'إدارة المواد',
        'chat.planning': 'الجدول',
        'chat.prof_section': 'فضاء الأستاذ',
        'chat.my_planning': 'جدولي',
        'chat.my_subjects': 'موادي',
        'chat.documents': 'الوثائق',
        'chat.student_section': 'فضاء الطالب',
        'chat.timetable': 'جدول الحصص',
        'chat.my_documents': 'وثائقي',
        'chat.recent': 'الأخيرة',
        'chat.assistant_title': 'مساعد FASTO',
        'chat.assistant_subtitle': 'مساعد الكلية الذكي',
        'chat.sources': 'المصادر:',
        'chat.copy': 'نسخ',
        'chat.fasto_ai': 'FASTO AI',

        'suggestion.timetable': 'جدول حصصي',
        'suggestion.certificate': 'شهادة مدرسية',
        'suggestion.grades': 'كشف نقاطي',
        'suggestion.scholarships': 'المنح المتاحة',
        'suggestion.programs': 'الاختصاصات المتاحة',
        'suggestion.registration': 'كيفية التسجيل',
        'suggestion.calendar': 'الرزنامة الأكاديمية',
        'suggestion.rules': 'النظام الداخلي',

        'form.title': 'منشئ الوثائق',
        'form.type': 'نوع الوثيقة',
        'form.name': 'الاسم الكامل',
        'form.name_placeholder': 'مثال: أحمد بن صالح',
        'form.format': 'الصيغة',
        'form.generate': 'إنشاء الوثيقة',
        'form.generating': 'جار الإنشاء...',
        'form.cancel': 'إلغاء',
        'form.academic_year': 'السنة الجامعية',
        'form.academic_year_placeholder': 'مثال: 2024/2025',
        'form.address': 'العنوان الكامل',
        'form.company': 'مؤسسة التربص',
        'form.duration': 'مدة التربص',
        'form.duration_placeholder': 'مثال: 3 أشهر',
        'form.recipient': 'الجهة المرسل إليها / الموضوع',
        'form.additional': 'معلومات إضافية',
        'form.additional_placeholder': 'أضف تفاصيل عند الحاجة...',

        'doc.attest_travail': 'شهادة عمل',
        'doc.attest_scolarite': 'شهادة دراسية',
        'doc.attest_residence': 'شهادة إقامة',
        'doc.generated': 'تم إنشاء الوثيقة.',
        'doc.download': 'تحميل الوثيقة',
        'doc.error': 'حدث خطأ أثناء إنشاء الوثيقة.',
        'doc.name_required': 'يرجى إدخال الاسم الكامل',
        'doc.certificat_scolarite': 'شهادة ترسيم',
        'doc.releve_notes': 'كشف النقاط',
        'doc.attest_stage': 'شهادة تربص',
        'doc.attest_presence': 'شهادة حضور',
        'doc.attest_residence_label': 'شهادة إقامة',
        'doc.copie_conforme': 'نسخة مطابقة',
        'doc.declaration_honneur': 'تصريح شرفي',
        'doc.lettre_motivation': 'رسالة تحفيز',
        'doc.lettre_demande': 'رسالة طلب',
        'doc.lettre_reclamation': 'رسالة تظلم',
        'doc.group_academic': 'أكاديمي',
        'doc.group_admin': 'إداري',
        'doc.group_letters': 'رسائل',

        'role.admin': 'مدير',
        'role.professor': 'أستاذ',
        'role.student': 'طالب',

        'page.admin': 'لوحة تحكم المدير',
        'page.chat': 'المساعد الذكي',
        'page.login': 'تسجيل الدخول',
        'page.register': 'إنشاء حساب',
        'page.default': 'بوابة FASTO'
      }
    };

    const cleanLang = this.getLanguage();
    if (cleanTranslations[cleanLang]?.[key]) {
      return cleanTranslations[cleanLang][key];
    }
    if (cleanTranslations['fr'][key]) {
      return cleanTranslations['fr'][key];
    }

    const translations: Record<string, Record<string, string>> = {

      fr: {
        // â”€â”€â”€ Header â”€â”€â”€
        'app.title': 'Assistant Administratif',
        'app.subtitle': 'Portail Administratif',
        'app.status': 'En ligne',
        'app.admin': 'Tableau de bord',
        'app.logout': 'DÃ©connexion',
        'app.newchat': 'Nouvelle conversation',
        'app.history': 'Conversations rÃ©centes',
        'app.noconv': 'Aucune conversation',
        'app.admin_role': 'Administrateur',
        'app.user_role': 'Utilisateur',
        'app.profile': 'Mon profil',
        'app.settings': 'ParamÃ¨tres',
        'app.language': 'Langue',
        'app.notifications': 'Notifications',

        // â”€â”€â”€ Login â”€â”€â”€
        'login.title': 'Connectez-vous Ã  votre compte',
        'login.subtitle': 'Portail Administratif Intelligent',
        'login.username': "Nom d'utilisateur",
        'login.username_placeholder': 'votre_identifiant',
        'login.password': 'Mot de passe',
        'login.forgot': 'OubliÃ© ?',
        'login.remember': 'Rester connectÃ©',
        'login.btn': 'Se connecter',
        'login.error': "Nom d'utilisateur ou mot de passe incorrect",
        'login.empty_fields': 'Veuillez remplir tous les champs',
        'login.no_account': 'Pas encore membre ?',
        'login.register': "CrÃ©er un compte",
        'login.or': 'OU',
        'login.footer': 'Â© 2026 FacultÃ© des Sciences â€” Projet PFE FASTO',

        // â”€â”€â”€ Register â”€â”€â”€
        'register.title': 'CrÃ©er un nouveau compte',
        'register.choose_role': 'Choisissez votre rÃ´le',
        'register.student': 'Ã‰tudiant',
        'register.professor': 'Professeur',
        'register.student_id': 'Identifiant Ã‰tudiant',
        'register.prof_id': 'Identifiant Professeur',
        'register.id_placeholder': 'Identifiant fourni par l\'administration',
        'register.personal_info': 'Informations Personnelles',
        'register.first_name': 'PrÃ©nom',
        'register.last_name': 'Nom',
        'register.email': 'Email',
        'register.cin': 'NumÃ©ro CIN',
        'register.phone': 'TÃ©lÃ©phone',
        'register.address': 'Adresse',
        'register.gender': 'Genre',
        'register.male': 'Homme',
        'register.female': 'Femme',
        'register.academic_info': 'Informations AcadÃ©miques',
        'register.field_of_study': 'FiliÃ¨re',
        'register.bac_type': 'Type de BaccalaurÃ©at',
        'register.scholarship': 'Boursier',
        'register.department': 'DÃ©partement',
        'register.account_info': 'Informations du Compte',
        'register.username': "Nom d'utilisateur",
        'register.password': 'Mot de passe',
        'register.confirm_password': 'Confirmer le mot de passe',
        'register.accept_terms': 'J\'accepte les conditions d\'utilisation',
        'register.btn': "S'inscrire",
        'register.error_match': 'Les mots de passe ne correspondent pas',
        'register.error_length': 'Le mot de passe doit contenir au moins 6 caractÃ¨res',
        'register.success': 'Compte crÃ©Ã© avec succÃ¨s ! Redirection...',
        'register.error_used': 'Username ou email dÃ©jÃ  utilisÃ©',
        'register.already_account': 'DÃ©jÃ  un compte ?',
        'register.login': 'Se connecter',
        'register.yes': 'Oui',
        'register.no': 'Non',

        // â”€â”€â”€ Admin â”€â”€â”€
        'admin.chat_btn': 'Chat',
        'admin.tab_stats': 'Statistiques',
        'admin.tab_users': 'Utilisateurs',
        'admin.tab_messages': 'Conversations',
        'admin.tab_docs': 'Documents',
        'admin.tab_notes': 'Notes',
        'admin.tab_identity': 'Identifiants',
        'admin.stat_users': 'Utilisateurs',
        'admin.stat_messages': 'Messages',
        'admin.stat_docs': 'Documents',
        'admin.stat_students': 'Ã‰tudiants',
        'admin.stat_professors': 'Professeurs',
        'admin.stat_admins': 'Admins',
        'admin.title_users': 'Liste des utilisateurs',
        'admin.title_messages': 'Historique des conversations',
        'admin.title_docs': 'Documents gÃ©nÃ©rÃ©s',
        'admin.title_notes': 'Notes des Ã©tudiants',
        'admin.title_identity': 'GÃ©nÃ©rer un identifiant',
        'admin.th_id': 'ID',
        'admin.th_username': "Nom d'utilisateur",
        'admin.th_email': 'Email',
        'admin.th_role': 'RÃ´le',
        'admin.th_date': 'Date',
        'admin.th_action': 'Action',
        'admin.th_user': 'Utilisateur',
        'admin.th_message': 'Message',
        'admin.th_response': 'RÃ©ponse',
        'admin.th_intent': 'Intention',
        'admin.th_lang': 'Langue',
        'admin.th_type': 'Type',
        'admin.th_name': 'Nom',
        'admin.th_format': 'Format',
        'admin.th_status': 'Statut',
        'admin.btn_delete': 'Supprimer',
        'admin.btn_generate': 'GÃ©nÃ©rer',
        'admin.btn_copy': 'Copier',
        'admin.fill_all': 'Veuillez remplir tous les champs.',

        // â”€â”€â”€ Chat â”€â”€â”€
        'chat.placeholder': 'Posez votre question Ã  FASTO...',
        'chat.welcome_title': "Comment puis-je vous aider aujourd'hui ?",
        'chat.welcome_desc': 'Je peux vous renseigner sur le calendrier acadÃ©mique, gÃ©nÃ©rer des documents administratifs ou consulter vos notes.',
        'chat.welcome': 'Bonjour ! Je suis votre assistant administratif intelligent.',
        'chat.attach': 'ðŸ“Ž',
        'chat.new_assistant': 'Nouvel Assistant',
        'chat.admin_section': 'Administration',
        'chat.dashboard': 'Tableau de bord',
        'chat.faculty_mgmt': 'Gestion FacultÃ©',
        'chat.rooms_mgmt': 'Gestion Salles',
        'chat.subjects_mgmt': 'Gestion MatiÃ¨res',
        'chat.planning': 'Planning',
        'chat.prof_section': 'Espace Professeur',
        'chat.my_planning': 'Mon Planning',
        'chat.my_subjects': 'Mes MatiÃ¨res',
        'chat.documents': 'Documents',
        'chat.student_section': 'Espace Ã‰tudiant',
        'chat.timetable': 'Emploi du temps',
        'chat.my_documents': 'Mes Documents',
        'chat.recent': 'RÃ©cent',
        'chat.assistant_title': 'Assistant FASTO',
        'chat.assistant_subtitle': 'Intelligence Artificielle de la FacultÃ©',
        'chat.sources': 'Sources :',
        'chat.copy': 'Copier',
        'chat.fasto_ai': 'FASTO AI',

        // â”€â”€â”€ Quick suggestions â”€â”€â”€
        'suggestion.timetable': 'ðŸ“… Mon emploi du temps',
        'suggestion.certificate': 'ðŸ“„ Attestation de scolaritÃ©',
        'suggestion.grades': 'ðŸ“Š Mon relevÃ© de notes',
        'suggestion.scholarships': 'ðŸ… Bourses disponibles',
        'suggestion.programs': 'ðŸŽ“ FiliÃ¨res proposÃ©es',
        'suggestion.registration': 'ðŸ“ Comment s\'inscrire',
        'suggestion.calendar': 'ðŸ“… Calendrier acadÃ©mique',
        'suggestion.rules': 'ðŸ“œ RÃ¨glement intÃ©rieur',

        // â”€â”€â”€ Document Panel â”€â”€â”€
        'form.title': 'ðŸ“„ GÃ©nÃ©rateur de Documents',
        'form.type': 'Type de document',
        'form.name': 'Nom Complet',
        'form.name_placeholder': 'Ex: Ahmed Ben Salah',
        'form.format': 'Format',
        'form.generate': 'âœ¨ GÃ©nÃ©rer le document',
        'form.generating': 'GÃ©nÃ©ration en cours...',
        'form.cancel': 'Annuler',
        'form.academic_year': 'AnnÃ©e Universitaire',
        'form.address': 'Adresse ComplÃ¨te',
        'form.company': 'Entreprise de stage',
        'form.duration': 'DurÃ©e du stage',
        'form.recipient': 'Destinataire / Objet',
        'form.additional': 'Informations supplÃ©mentaires',
        'form.additional_placeholder': 'Ajoutez des prÃ©cisions si nÃ©cessaire...',
        'doc.attest_travail': 'Attestation de travail',
        'doc.attest_scolarite': 'Attestation de scolaritÃ©',
        'doc.attest_residence': 'Attestation de rÃ©sidence',
        'doc.generated': 'âœ… Votre document a Ã©tÃ© gÃ©nÃ©rÃ© ! Cliquez pour tÃ©lÃ©charger.',
        'doc.download': 'ðŸ“¥ TÃ©lÃ©charger le document',
        'doc.error': 'Erreur lors de la gÃ©nÃ©ration du document.',
        'doc.name_required': 'Veuillez entrer votre nom complet',
        'doc.certificat_scolarite': 'Certificat de scolaritÃ©',
        'doc.releve_notes': 'RelevÃ© de notes',
        'doc.attest_stage': 'Attestation de stage',
        'doc.attest_presence': 'Attestation de prÃ©sence',
        'doc.attest_residence_label': 'Attestation de rÃ©sidence',
        'doc.copie_conforme': 'Copie conforme',
        'doc.declaration_honneur': "DÃ©claration sur l'honneur",
        'doc.lettre_motivation': 'Lettre de motivation',
        'doc.lettre_demande': 'Lettre de demande',
        'doc.lettre_reclamation': 'Lettre de rÃ©clamation',
        'doc.group_academic': 'ðŸ“œ AcadÃ©mique',
        'doc.group_admin': 'ðŸ“ Administratif',
        'doc.group_letters': 'âœ‰ï¸ Lettres',

        // â”€â”€â”€ Roles â”€â”€â”€
        'role.admin': 'Administrateur',
        'role.professor': 'Professeur',
        'role.student': 'Ã‰tudiant',

        // â”€â”€â”€ Page titles â”€â”€â”€
        'page.admin': 'Tableau de Bord Admin',
        'page.chat': 'Assistant IA',
        'page.login': 'Connexion',
        'page.register': 'Inscription',
        'page.default': 'Portail FASTO',
      },

      // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
      // ENGLISH
      // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
      en: {
        // â”€â”€â”€ Header â”€â”€â”€
        'app.title': 'Administrative Assistant',
        'app.subtitle': 'Administrative Portal',
        'app.status': 'Online',
        'app.admin': 'Dashboard',
        'app.logout': 'Sign Out',
        'app.newchat': 'New conversation',
        'app.history': 'Recent conversations',
        'app.noconv': 'No conversations',
        'app.admin_role': 'Administrator',
        'app.user_role': 'User',
        'app.profile': 'My Profile',
        'app.settings': 'Settings',
        'app.language': 'Language',
        'app.notifications': 'Notifications',

        // â”€â”€â”€ Login â”€â”€â”€
        'login.title': 'Sign in to your account',
        'login.subtitle': 'Intelligent Administrative Portal',
        'login.username': 'Username',
        'login.username_placeholder': 'your_username',
        'login.password': 'Password',
        'login.forgot': 'Forgot?',
        'login.remember': 'Remember me',
        'login.btn': 'Sign In',
        'login.error': 'Incorrect username or password',
        'login.empty_fields': 'Please fill in all fields',
        'login.no_account': 'Not a member yet?',
        'login.register': 'Create an account',
        'login.or': 'OR',
        'login.footer': 'Â© 2026 Faculty of Sciences â€” PFE Project FASTO',

        // â”€â”€â”€ Register â”€â”€â”€
        'register.title': 'Create a new account',
        'register.choose_role': 'Choose your role',
        'register.student': 'Student',
        'register.professor': 'Professor',
        'register.student_id': 'Student ID',
        'register.prof_id': 'Professor ID',
        'register.id_placeholder': 'ID provided by administration',
        'register.personal_info': 'Personal Information',
        'register.first_name': 'First Name',
        'register.last_name': 'Last Name',
        'register.email': 'Email',
        'register.cin': 'National ID Number',
        'register.phone': 'Phone',
        'register.address': 'Address',
        'register.gender': 'Gender',
        'register.male': 'Male',
        'register.female': 'Female',
        'register.academic_info': 'Academic Information',
        'register.field_of_study': 'Field of Study',
        'register.bac_type': 'High School Diploma Type',
        'register.scholarship': 'Scholarship Holder',
        'register.department': 'Department',
        'register.account_info': 'Account Information',
        'register.username': 'Username',
        'register.password': 'Password',
        'register.confirm_password': 'Confirm Password',
        'register.accept_terms': 'I accept the terms of use',
        'register.btn': 'Sign Up',
        'register.error_match': 'Passwords do not match',
        'register.error_length': 'Password must be at least 6 characters',
        'register.success': 'Account created successfully! Redirecting...',
        'register.error_used': 'Username or email already in use',
        'register.already_account': 'Already have an account?',
        'register.login': 'Sign In',
        'register.yes': 'Yes',
        'register.no': 'No',

        // â”€â”€â”€ Admin â”€â”€â”€
        'admin.chat_btn': 'Chat',
        'admin.tab_stats': 'Statistics',
        'admin.tab_users': 'Users',
        'admin.tab_messages': 'Conversations',
        'admin.tab_docs': 'Documents',
        'admin.tab_notes': 'Grades',
        'admin.tab_identity': 'Identifiers',
        'admin.stat_users': 'Users',
        'admin.stat_messages': 'Messages',
        'admin.stat_docs': 'Documents',
        'admin.stat_students': 'Students',
        'admin.stat_professors': 'Professors',
        'admin.stat_admins': 'Admins',
        'admin.title_users': 'User List',
        'admin.title_messages': 'Conversation History',
        'admin.title_docs': 'Generated Documents',
        'admin.title_notes': 'Student Grades',
        'admin.title_identity': 'Generate Identifier',
        'admin.th_id': 'ID',
        'admin.th_username': 'Username',
        'admin.th_email': 'Email',
        'admin.th_role': 'Role',
        'admin.th_date': 'Date',
        'admin.th_action': 'Action',
        'admin.th_user': 'User',
        'admin.th_message': 'Message',
        'admin.th_response': 'Response',
        'admin.th_intent': 'Intent',
        'admin.th_lang': 'Language',
        'admin.th_type': 'Type',
        'admin.th_name': 'Name',
        'admin.th_format': 'Format',
        'admin.th_status': 'Status',
        'admin.btn_delete': 'Delete',
        'admin.btn_generate': 'Generate',
        'admin.btn_copy': 'Copy',
        'admin.fill_all': 'Please fill in all fields.',

        // â”€â”€â”€ Chat â”€â”€â”€
        'chat.placeholder': 'Ask FASTO your question...',
        'chat.welcome_title': 'How can I help you today?',
        'chat.welcome_desc': 'I can help you with the academic calendar, generate administrative documents, or check your grades.',
        'chat.welcome': 'Hello! I am your intelligent administrative assistant.',
        'chat.attach': 'ðŸ“Ž',
        'chat.new_assistant': 'New Assistant',
        'chat.admin_section': 'Administration',
        'chat.dashboard': 'Dashboard',
        'chat.faculty_mgmt': 'Faculty Management',
        'chat.rooms_mgmt': 'Room Management',
        'chat.subjects_mgmt': 'Subject Management',
        'chat.planning': 'Schedule',
        'chat.prof_section': 'Professor Area',
        'chat.my_planning': 'My Schedule',
        'chat.my_subjects': 'My Subjects',
        'chat.documents': 'Documents',
        'chat.student_section': 'Student Area',
        'chat.timetable': 'Timetable',
        'chat.my_documents': 'My Documents',
        'chat.recent': 'Recent',
        'chat.assistant_title': 'FASTO Assistant',
        'chat.assistant_subtitle': 'Faculty Artificial Intelligence',
        'chat.sources': 'Sources:',
        'chat.copy': 'Copy',
        'chat.fasto_ai': 'FASTO AI',

        // â”€â”€â”€ Quick suggestions â”€â”€â”€
        'suggestion.timetable': 'ðŸ“… My timetable',
        'suggestion.certificate': 'ðŸ“„ School certificate',
        'suggestion.grades': 'ðŸ“Š My transcript',
        'suggestion.scholarships': 'ðŸ… Available scholarships',
        'suggestion.programs': 'ðŸŽ“ Available programs',
        'suggestion.registration': 'ðŸ“ How to register',
        'suggestion.calendar': 'ðŸ“… Academic calendar',
        'suggestion.rules': 'ðŸ“œ Internal regulations',

        // â”€â”€â”€ Document Panel â”€â”€â”€
        'form.title': 'ðŸ“„ Document Generator',
        'form.type': 'Document Type',
        'form.name': 'Full Name',
        'form.name_placeholder': 'e.g: John Smith',
        'form.format': 'Format',
        'form.generate': 'âœ¨ Generate Document',
        'form.generating': 'Generating...',
        'form.cancel': 'Cancel',
        'form.academic_year': 'Academic Year',
        'form.address': 'Full Address',
        'form.company': 'Internship Company',
        'form.duration': 'Internship Duration',
        'form.recipient': 'Recipient / Subject',
        'form.additional': 'Additional Information',
        'form.additional_placeholder': 'Add details if necessary...',
        'doc.attest_travail': 'Work Certificate',
        'doc.attest_scolarite': 'School Certificate',
        'doc.attest_residence': 'Residence Certificate',
        'doc.generated': 'âœ… Your document has been generated! Click to download.',
        'doc.download': 'ðŸ“¥ Download Document',
        'doc.error': 'Error generating the document.',
        'doc.name_required': 'Please enter your full name',
        'doc.certificat_scolarite': 'School Certificate',
        'doc.releve_notes': 'Transcript',
        'doc.attest_stage': 'Internship Certificate',
        'doc.attest_presence': 'Attendance Certificate',
        'doc.attest_residence_label': 'Residence Certificate',
        'doc.copie_conforme': 'Certified Copy',
        'doc.declaration_honneur': 'Sworn Statement',
        'doc.lettre_motivation': 'Cover Letter',
        'doc.lettre_demande': 'Request Letter',
        'doc.lettre_reclamation': 'Complaint Letter',
        'doc.group_academic': 'ðŸ“œ Academic',
        'doc.group_admin': 'ðŸ“ Administrative',
        'doc.group_letters': 'âœ‰ï¸ Letters',

        // â”€â”€â”€ Roles â”€â”€â”€
        'role.admin': 'Administrator',
        'role.professor': 'Professor',
        'role.student': 'Student',

        // â”€â”€â”€ Page titles â”€â”€â”€
        'page.admin': 'Admin Dashboard',
        'page.chat': 'AI Assistant',
        'page.login': 'Sign In',
        'page.register': 'Sign Up',
        'page.default': 'FASTO Portal',
      },

      // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
      // ARABIC
      // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
      ar: {
        // â”€â”€â”€ Header â”€â”€â”€
        'app.title': 'Ø§Ù„Ù…Ø³Ø§Ø¹Ø¯ Ø§Ù„Ø¥Ø¯Ø§Ø±ÙŠ',
        'app.subtitle': 'Ø§Ù„Ø¨ÙˆØ§Ø¨Ø© Ø§Ù„Ø¥Ø¯Ø§Ø±ÙŠØ©',
        'app.status': 'Ù…ØªØµÙ„',
        'app.admin': 'Ù„ÙˆØ­Ø© Ø§Ù„ØªØ­ÙƒÙ…',
        'app.logout': 'Ø®Ø±ÙˆØ¬',
        'app.newchat': 'Ù…Ø­Ø§Ø¯Ø«Ø© Ø¬Ø¯ÙŠØ¯Ø©',
        'app.history': 'Ø§Ù„Ù…Ø­Ø§Ø¯Ø«Ø§Øª Ø§Ù„Ø£Ø®ÙŠØ±Ø©',
        'app.noconv': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ù…Ø­Ø§Ø¯Ø«Ø§Øª',
        'app.admin_role': 'Ù…Ø¯ÙŠØ±',
        'app.user_role': 'Ù…Ø³ØªØ®Ø¯Ù…',
        'app.profile': 'Ù…Ù„ÙÙŠ Ø§Ù„Ø´Ø®ØµÙŠ',
        'app.settings': 'Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª',
        'app.language': 'Ø§Ù„Ù„ØºØ©',
        'app.notifications': 'Ø§Ù„Ø¥Ø´Ø¹Ø§Ø±Ø§Øª',

        // â”€â”€â”€ Login â”€â”€â”€
        'login.title': 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ø¥Ù„Ù‰ Ø­Ø³Ø§Ø¨Ùƒ',
        'login.subtitle': 'Ø§Ù„Ø¨ÙˆØ§Ø¨Ø© Ø§Ù„Ø¥Ø¯Ø§Ø±ÙŠØ© Ø§Ù„Ø°ÙƒÙŠØ©',
        'login.username': 'Ø§Ø³Ù… Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…',
        'login.username_placeholder': 'Ø§Ø³Ù…_Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…',
        'login.password': 'ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±',
        'login.forgot': 'Ù†Ø³ÙŠØªØŸ',
        'login.remember': 'ØªØ°ÙƒØ±Ù†ÙŠ',
        'login.btn': 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„',
        'login.error': 'Ø§Ø³Ù… Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù… Ø£Ùˆ ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± ØºÙŠØ± ØµØ­ÙŠØ­Ø©',
        'login.empty_fields': 'Ø§Ù„Ø±Ø¬Ø§Ø¡ ØªØ¹Ø¨Ø¦Ø© Ø¬Ù…ÙŠØ¹ Ø§Ù„Ø­Ù‚ÙˆÙ„',
        'login.no_account': 'Ù„ÙŠØ³ Ù„Ø¯ÙŠÙƒ Ø­Ø³Ø§Ø¨ Ø¨Ø¹Ø¯ØŸ',
        'login.register': 'Ø¥Ù†Ø´Ø§Ø¡ Ø­Ø³Ø§Ø¨',
        'login.or': 'Ø£Ùˆ',
        'login.footer': 'Â© 2026 ÙƒÙ„ÙŠØ© Ø§Ù„Ø¹Ù„ÙˆÙ… â€” Ù…Ø´Ø±ÙˆØ¹ ØªØ®Ø±Ø¬ FASTO',

        // â”€â”€â”€ Register â”€â”€â”€
        'register.title': 'Ø¥Ù†Ø´Ø§Ø¡ Ø­Ø³Ø§Ø¨ Ø¬Ø¯ÙŠØ¯',
        'register.choose_role': 'Ø§Ø®ØªØ± Ø¯ÙˆØ±Ùƒ',
        'register.student': 'Ø·Ø§Ù„Ø¨',
        'register.professor': 'Ø£Ø³ØªØ§Ø°',
        'register.student_id': 'Ù…Ø¹Ø±Ù Ø§Ù„Ø·Ø§Ù„Ø¨',
        'register.prof_id': 'Ù…Ø¹Ø±Ù Ø§Ù„Ø£Ø³ØªØ§Ø°',
        'register.id_placeholder': 'Ø§Ù„Ù…Ø¹Ø±Ù Ø§Ù„Ù…Ù‚Ø¯Ù… Ù…Ù† Ø§Ù„Ø¥Ø¯Ø§Ø±Ø©',
        'register.personal_info': 'Ø§Ù„Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø§Ù„Ø´Ø®ØµÙŠØ©',
        'register.first_name': 'Ø§Ù„Ø§Ø³Ù…',
        'register.last_name': 'Ø§Ù„Ù„Ù‚Ø¨',
        'register.email': 'Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ',
        'register.cin': 'Ø±Ù‚Ù… Ø¨Ø·Ø§Ù‚Ø© Ø§Ù„ØªØ¹Ø±ÙŠÙ',
        'register.phone': 'Ø§Ù„Ù‡Ø§ØªÙ',
        'register.address': 'Ø§Ù„Ø¹Ù†ÙˆØ§Ù†',
        'register.gender': 'Ø§Ù„Ø¬Ù†Ø³',
        'register.male': 'Ø°ÙƒØ±',
        'register.female': 'Ø£Ù†Ø«Ù‰',
        'register.academic_info': 'Ø§Ù„Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø§Ù„Ø£ÙƒØ§Ø¯ÙŠÙ…ÙŠØ©',
        'register.field_of_study': 'Ø§Ù„ØªØ®ØµØµ',
        'register.bac_type': 'Ù†ÙˆØ¹ Ø§Ù„Ø¨ÙƒØ§Ù„ÙˆØ±ÙŠØ§',
        'register.scholarship': 'Ù…Ù†Ø­Ø©',
        'register.department': 'Ø§Ù„Ù‚Ø³Ù…',
        'register.account_info': 'Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø§Ù„Ø­Ø³Ø§Ø¨',
        'register.username': 'Ø§Ø³Ù… Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…',
        'register.password': 'ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±',
        'register.confirm_password': 'ØªØ£ÙƒÙŠØ¯ ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±',
        'register.accept_terms': 'Ø£ÙˆØ§ÙÙ‚ Ø¹Ù„Ù‰ Ø´Ø±ÙˆØ· Ø§Ù„Ø§Ø³ØªØ®Ø¯Ø§Ù…',
        'register.btn': 'Ø¥Ù†Ø´Ø§Ø¡ Ø­Ø³Ø§Ø¨',
        'register.error_match': 'ÙƒÙ„Ù…Ø§Øª Ø§Ù„Ù…Ø±ÙˆØ± ØºÙŠØ± Ù…ØªØ·Ø§Ø¨Ù‚Ø©',
        'register.error_length': 'ÙŠØ¬Ø¨ Ø£Ù† ØªØ­ØªÙˆÙŠ ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± Ø¹Ù„Ù‰ 6 Ø£Ø­Ø±Ù Ø¹Ù„Ù‰ Ø§Ù„Ø£Ù‚Ù„',
        'register.success': 'ØªÙ… Ø¥Ù†Ø´Ø§Ø¡ Ø§Ù„Ø­Ø³Ø§Ø¨ Ø¨Ù†Ø¬Ø§Ø­! Ø¬Ø§Ø±ÙŠ Ø§Ù„ØªÙˆØ¬ÙŠÙ‡...',
        'register.error_used': 'Ø§Ø³Ù… Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù… Ø£Ùˆ Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ Ù…Ø³ØªØ®Ø¯Ù… Ø¨Ø§Ù„ÙØ¹Ù„',
        'register.already_account': 'Ù„Ø¯ÙŠÙƒ Ø­Ø³Ø§Ø¨ Ø¨Ø§Ù„ÙØ¹Ù„ØŸ',
        'register.login': 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„',
        'register.yes': 'Ù†Ø¹Ù…',
        'register.no': 'Ù„Ø§',

        // â”€â”€â”€ Admin â”€â”€â”€
        'admin.chat_btn': 'Ù…Ø­Ø§Ø¯Ø«Ø©',
        'admin.tab_stats': 'Ø¥Ø­ØµØ§Ø¦ÙŠØ§Øª',
        'admin.tab_users': 'Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…ÙŠÙ†',
        'admin.tab_messages': 'Ø§Ù„Ù…Ø­Ø§Ø¯Ø«Ø§Øª',
        'admin.tab_docs': 'Ø§Ù„ÙˆØ«Ø§Ø¦Ù‚',
        'admin.tab_notes': 'Ø§Ù„Ù†ØªØ§Ø¦Ø¬',
        'admin.tab_identity': 'Ø§Ù„Ù…Ø¹Ø±ÙØ§Øª',
        'admin.stat_users': 'Ù…Ø³ØªØ®Ø¯Ù…ÙŠÙ†',
        'admin.stat_messages': 'Ø±Ø³Ø§Ø¦Ù„',
        'admin.stat_docs': 'ÙˆØ«Ø§Ø¦Ù‚',
        'admin.stat_students': 'Ø·Ù„Ø¨Ø©',
        'admin.stat_professors': 'Ø£Ø³Ø§ØªØ°Ø©',
        'admin.stat_admins': 'Ù…Ø¯Ø±Ø§Ø¡',
        'admin.title_users': 'Ù‚Ø§Ø¦Ù…Ø© Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…ÙŠÙ†',
        'admin.title_messages': 'Ø³Ø¬Ù„ Ø§Ù„Ù…Ø­Ø§Ø¯Ø«Ø§Øª',
        'admin.title_docs': 'Ø§Ù„ÙˆØ«Ø§Ø¦Ù‚ Ø§Ù„Ù…Ù†Ø´Ø£Ø©',
        'admin.title_notes': 'Ù†ØªØ§Ø¦Ø¬ Ø§Ù„Ø·Ù„Ø¨Ø©',
        'admin.title_identity': 'Ø¥Ù†Ø´Ø§Ø¡ Ù…Ø¹Ø±Ù',
        'admin.th_id': 'Ø§Ù„Ø±Ù‚Ù…',
        'admin.th_username': 'Ø§Ø³Ù… Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…',
        'admin.th_email': 'Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ',
        'admin.th_role': 'Ø§Ù„Ø¯ÙˆØ±',
        'admin.th_date': 'Ø§Ù„ØªØ§Ø±ÙŠØ®',
        'admin.th_action': 'Ø¥Ø¬Ø±Ø§Ø¡',
        'admin.th_user': 'Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…',
        'admin.th_message': 'Ø§Ù„Ø±Ø³Ø§Ù„Ø©',
        'admin.th_response': 'Ø§Ù„Ø±Ø¯',
        'admin.th_intent': 'Ø§Ù„Ù†ÙŠØ©',
        'admin.th_lang': 'Ø§Ù„Ù„ØºØ©',
        'admin.th_type': 'Ø§Ù„Ù†ÙˆØ¹',
        'admin.th_name': 'Ø§Ù„Ø§Ø³Ù…',
        'admin.th_format': 'Ø§Ù„ØµÙŠØºØ©',
        'admin.th_status': 'Ø§Ù„Ø­Ø§Ù„Ø©',
        'admin.btn_delete': 'Ø­Ø°Ù',
        'admin.btn_generate': 'Ø¥Ù†Ø´Ø§Ø¡',
        'admin.btn_copy': 'Ù†Ø³Ø®',
        'admin.fill_all': 'Ø§Ù„Ø±Ø¬Ø§Ø¡ Ù…Ù„Ø¡ Ø¬Ù…ÙŠØ¹ Ø§Ù„Ø­Ù‚ÙˆÙ„.',

        // â”€â”€â”€ Chat â”€â”€â”€
        'chat.placeholder': 'Ø§ÙƒØªØ¨ Ø³Ø¤Ø§Ù„Ùƒ Ù„Ù€ FASTO...',
        'chat.welcome_title': 'ÙƒÙŠÙ ÙŠÙ…ÙƒÙ†Ù†ÙŠ Ù…Ø³Ø§Ø¹Ø¯ØªÙƒ Ø§Ù„ÙŠÙˆÙ…ØŸ',
        'chat.welcome_desc': 'ÙŠÙ…ÙƒÙ†Ù†ÙŠ Ù…Ø³Ø§Ø¹Ø¯ØªÙƒ Ø¨Ø§Ù„Ø±Ø²Ù†Ø§Ù…Ø© Ø§Ù„Ø£ÙƒØ§Ø¯ÙŠÙ…ÙŠØ© ÙˆØ¥Ù†Ø´Ø§Ø¡ Ø§Ù„ÙˆØ«Ø§Ø¦Ù‚ Ø§Ù„Ø¥Ø¯Ø§Ø±ÙŠØ© ÙˆÙ…Ø±Ø§Ø¬Ø¹Ø© Ù†ØªØ§Ø¦Ø¬Ùƒ.',
        'chat.welcome': 'Ù…Ø±Ø­Ø¨Ø§Ù‹! Ø£Ù†Ø§ Ù…Ø³Ø§Ø¹Ø¯Ùƒ Ø§Ù„Ø¥Ø¯Ø§Ø±ÙŠ Ø§Ù„Ø°ÙƒÙŠ.',
        'chat.attach': 'ðŸ“Ž',
        'chat.new_assistant': 'Ù…Ø³Ø§Ø¹Ø¯ Ø¬Ø¯ÙŠØ¯',
        'chat.admin_section': 'Ø§Ù„Ø¥Ø¯Ø§Ø±Ø©',
        'chat.dashboard': 'Ù„ÙˆØ­Ø© Ø§Ù„ØªØ­ÙƒÙ…',
        'chat.faculty_mgmt': 'Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„ÙƒÙ„ÙŠØ©',
        'chat.rooms_mgmt': 'Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ù‚Ø§Ø¹Ø§Øª',
        'chat.subjects_mgmt': 'Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ù…ÙˆØ§Ø¯',
        'chat.planning': 'Ø§Ù„Ø¨Ø±Ù†Ø§Ù…Ø¬',
        'chat.prof_section': 'ÙØ¶Ø§Ø¡ Ø§Ù„Ø£Ø³ØªØ§Ø°',
        'chat.my_planning': 'Ø¨Ø±Ù†Ø§Ù…Ø¬ÙŠ',
        'chat.my_subjects': 'Ù…ÙˆØ§Ø¯ÙŠ',
        'chat.documents': 'Ø§Ù„ÙˆØ«Ø§Ø¦Ù‚',
        'chat.student_section': 'ÙØ¶Ø§Ø¡ Ø§Ù„Ø·Ø§Ù„Ø¨',
        'chat.timetable': 'Ø¬Ø¯ÙˆÙ„ Ø§Ù„Ø­ØµØµ',
        'chat.my_documents': 'ÙˆØ«Ø§Ø¦Ù‚ÙŠ',
        'chat.recent': 'Ø§Ù„Ø£Ø®ÙŠØ±Ø©',
        'chat.assistant_title': 'Ù…Ø³Ø§Ø¹Ø¯ FASTO',
        'chat.assistant_subtitle': 'Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ Ù„Ù„ÙƒÙ„ÙŠØ©',
        'chat.sources': 'Ø§Ù„Ù…ØµØ§Ø¯Ø±:',
        'chat.copy': 'Ù†Ø³Ø®',
        'chat.fasto_ai': 'FASTO AI',

        // â”€â”€â”€ Quick suggestions â”€â”€â”€
        'suggestion.timetable': 'ðŸ“… Ø¬Ø¯ÙˆÙ„ Ø­ØµØµÙŠ',
        'suggestion.certificate': 'ðŸ“„ Ø´Ù‡Ø§Ø¯Ø© Ø¯Ø±Ø§Ø³ÙŠØ©',
        'suggestion.grades': 'ðŸ“Š ÙƒØ´Ù Ù†Ù‚Ø§Ø·ÙŠ',
        'suggestion.scholarships': 'ðŸ… Ø§Ù„Ù…Ù†Ø­ Ø§Ù„Ù…ØªØ§Ø­Ø©',
        'suggestion.programs': 'ðŸŽ“ Ø§Ù„ØªØ®ØµØµØ§Øª Ø§Ù„Ù…ØªØ§Ø­Ø©',
        'suggestion.registration': 'ðŸ“ ÙƒÙŠÙÙŠØ© Ø§Ù„ØªØ³Ø¬ÙŠÙ„',
        'suggestion.calendar': 'ðŸ“… Ø§Ù„Ø±Ø²Ù†Ø§Ù…Ø© Ø§Ù„Ø£ÙƒØ§Ø¯ÙŠÙ…ÙŠØ©',
        'suggestion.rules': 'ðŸ“œ Ø§Ù„Ù†Ø¸Ø§Ù… Ø§Ù„Ø¯Ø§Ø®Ù„ÙŠ',

        // â”€â”€â”€ Document Panel â”€â”€â”€
        'form.title': 'ðŸ“„ Ù…Ù†Ø´Ø¦ Ø§Ù„ÙˆØ«Ø§Ø¦Ù‚',
        'form.type': 'Ù†ÙˆØ¹ Ø§Ù„ÙˆØ«ÙŠÙ‚Ø©',
        'form.name': 'Ø§Ù„Ø§Ø³Ù… Ø§Ù„ÙƒØ§Ù…Ù„',
        'form.name_placeholder': 'Ù…Ø«Ø§Ù„: Ø£Ø­Ù…Ø¯ Ø¨Ù† ØµØ§Ù„Ø­',
        'form.format': 'Ø§Ù„ØµÙŠØºØ©',
        'form.generate': 'âœ¨ Ø¥Ù†Ø´Ø§Ø¡ Ø§Ù„ÙˆØ«ÙŠÙ‚Ø©',
        'form.generating': 'Ø¬Ø§Ø±ÙŠ Ø§Ù„Ø¥Ù†Ø´Ø§Ø¡...',
        'form.cancel': 'Ø¥Ù„ØºØ§Ø¡',
        'form.academic_year': 'Ø§Ù„Ø³Ù†Ø© Ø§Ù„Ø¬Ø§Ù…Ø¹ÙŠØ©',
        'form.address': 'Ø§Ù„Ø¹Ù†ÙˆØ§Ù† Ø§Ù„ÙƒØ§Ù…Ù„',
        'form.company': 'Ù…Ø¤Ø³Ø³Ø© Ø§Ù„ØªØ±Ø¨Øµ',
        'form.duration': 'Ù…Ø¯Ø© Ø§Ù„ØªØ±Ø¨Øµ',
        'form.recipient': 'Ø§Ù„Ù…Ø±Ø³Ù„ Ø¥Ù„ÙŠÙ‡ / Ø§Ù„Ù…ÙˆØ¶ÙˆØ¹',
        'form.additional': 'Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø¥Ø¶Ø§ÙÙŠØ©',
        'form.additional_placeholder': 'Ø£Ø¶Ù ØªÙØ§ØµÙŠÙ„ Ø¥Ø°Ø§ Ù„Ø²Ù… Ø§Ù„Ø£Ù…Ø±...',
        'doc.attest_travail': 'Ø´Ù‡Ø§Ø¯Ø© Ø¹Ù…Ù„',
        'doc.attest_scolarite': 'Ø´Ù‡Ø§Ø¯Ø© Ø¯Ø±Ø§Ø³ÙŠØ©',
        'doc.attest_residence': 'Ø´Ù‡Ø§Ø¯Ø© Ø¥Ù‚Ø§Ù…Ø©',
        'doc.generated': 'âœ… ØªÙ… Ø¥Ù†Ø´Ø§Ø¡ ÙˆØ«ÙŠÙ‚ØªÙƒ! Ø§Ù†Ù‚Ø± Ù„Ù„ØªØ­Ù…ÙŠÙ„.',
        'doc.download': 'ðŸ“¥ ØªØ­Ù…ÙŠÙ„ Ø§Ù„ÙˆØ«ÙŠÙ‚Ø©',
        'doc.error': 'Ø®Ø·Ø£ ÙÙŠ Ø¥Ù†Ø´Ø§Ø¡ Ø§Ù„ÙˆØ«ÙŠÙ‚Ø©.',
        'doc.name_required': 'Ø§Ù„Ø±Ø¬Ø§Ø¡ Ø¥Ø¯Ø®Ø§Ù„ Ø§Ù„Ø§Ø³Ù… Ø§Ù„ÙƒØ§Ù…Ù„',
        'doc.certificat_scolarite': 'Ø´Ù‡Ø§Ø¯Ø© Ø§Ù„ØªÙ…Ø¯Ø±Ø³',
        'doc.releve_notes': 'ÙƒØ´Ù Ø§Ù„Ù†Ù‚Ø§Ø·',
        'doc.attest_stage': 'Ø´Ù‡Ø§Ø¯Ø© Ø§Ù„ØªØ±Ø¨Øµ',
        'doc.attest_presence': 'Ø´Ù‡Ø§Ø¯Ø© Ø§Ù„Ø­Ø¶ÙˆØ±',
        'doc.attest_residence_label': 'Ø´Ù‡Ø§Ø¯Ø© Ø§Ù„Ø¥Ù‚Ø§Ù…Ø©',
        'doc.copie_conforme': 'Ù†Ø³Ø®Ø© Ù…Ø·Ø§Ø¨Ù‚Ø©',
        'doc.declaration_honneur': 'ØªØµØ±ÙŠØ­ Ø´Ø±ÙÙŠ',
        'doc.lettre_motivation': 'Ø±Ø³Ø§Ù„Ø© Ø§Ù„ØªØ­ÙÙŠØ²',
        'doc.lettre_demande': 'Ø±Ø³Ø§Ù„Ø© Ø·Ù„Ø¨',
        'doc.lettre_reclamation': 'Ø±Ø³Ø§Ù„Ø© Ø´ÙƒÙˆÙ‰',
        'doc.group_academic': 'ðŸ“œ Ø£ÙƒØ§Ø¯ÙŠÙ…ÙŠ',
        'doc.group_admin': 'ðŸ“ Ø¥Ø¯Ø§Ø±ÙŠ',
        'doc.group_letters': 'âœ‰ï¸ Ø±Ø³Ø§Ø¦Ù„',

        // â”€â”€â”€ Roles â”€â”€â”€
        'role.admin': 'Ù…Ø¯ÙŠØ±',
        'role.professor': 'Ø£Ø³ØªØ§Ø°',
        'role.student': 'Ø·Ø§Ù„Ø¨',

        // â”€â”€â”€ Page titles â”€â”€â”€
        'page.admin': 'Ù„ÙˆØ­Ø© ØªØ­ÙƒÙ… Ø§Ù„Ù…Ø¯ÙŠØ±',
        'page.chat': 'Ø§Ù„Ù…Ø³Ø§Ø¹Ø¯ Ø§Ù„Ø°ÙƒÙŠ',
        'page.login': 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„',
        'page.register': 'Ø¥Ù†Ø´Ø§Ø¡ Ø­Ø³Ø§Ø¨',
        'page.default': 'Ø¨ÙˆØ§Ø¨Ø© FASTO',
      }
    };

    const lang = this.getLanguage();
    return translations[lang]?.[key] || translations['fr']?.[key] || key;
  }
}
