import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type Lang = 'fr' | 'en' | 'ar';

@Injectable({
  providedIn: 'root'
})
export class LanguageService {

  private static readonly LANGS: Lang[] = ['fr', 'en', 'ar'];

  private currentLang = new BehaviorSubject<Lang>(
    (localStorage.getItem('lang') as Lang) || 'fr'
  );

  currentLang$ = this.currentLang.asObservable();

  getLanguage(): Lang {
    return this.currentLang.getValue();
  }

  setLanguage(lang: Lang) {
    this.currentLang.next(lang);
    localStorage.setItem('lang', lang);
    document.dir = lang === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }

  /** Cycle through fr → en → ar → fr */
  toggleLanguage() {
    const idx = LanguageService.LANGS.indexOf(this.getLanguage());
    const next = LanguageService.LANGS[(idx + 1) % LanguageService.LANGS.length];
    this.setLanguage(next);
  }

  /** Get all supported languages for dropdown */
  getAvailableLanguages(): { code: Lang; label: string; flag: string }[] {
    return [
      { code: 'fr', label: 'Français', flag: '🇫🇷' },
      { code: 'en', label: 'English',  flag: '🇬🇧' },
      { code: 'ar', label: 'العربية',  flag: '🇸🇦' }
    ];
  }

  // ============================================
  // TRADUCTIONS COMPLÈTES — FR / EN / AR
  // ============================================
  t(key: string): string {
    const translations: Record<string, Record<string, string>> = {

      fr: {
        // ─── Header ───
        'app.title': 'Assistant Administratif',
        'app.subtitle': 'Portail Administratif',
        'app.status': 'En ligne',
        'app.admin': 'Tableau de bord',
        'app.logout': 'Déconnexion',
        'app.newchat': 'Nouvelle conversation',
        'app.history': 'Conversations récentes',
        'app.noconv': 'Aucune conversation',
        'app.admin_role': 'Administrateur',
        'app.user_role': 'Utilisateur',
        'app.profile': 'Mon profil',
        'app.settings': 'Paramètres',
        'app.language': 'Langue',

        // ─── Login ───
        'login.title': 'Connectez-vous à votre compte',
        'login.subtitle': 'Portail Administratif Intelligent',
        'login.username': "Nom d'utilisateur",
        'login.username_placeholder': 'votre_identifiant',
        'login.password': 'Mot de passe',
        'login.forgot': 'Oublié ?',
        'login.remember': 'Rester connecté',
        'login.btn': 'Se connecter',
        'login.error': "Nom d'utilisateur ou mot de passe incorrect",
        'login.empty_fields': 'Veuillez remplir tous les champs',
        'login.no_account': 'Pas encore membre ?',
        'login.register': "Créer un compte",
        'login.or': 'OU',
        'login.footer': '© 2026 Faculté des Sciences — Projet PFE FASTO',

        // ─── Register ───
        'register.title': 'Créer un nouveau compte',
        'register.choose_role': 'Choisissez votre rôle',
        'register.student': 'Étudiant',
        'register.professor': 'Professeur',
        'register.student_id': 'Identifiant Étudiant',
        'register.prof_id': 'Identifiant Professeur',
        'register.id_placeholder': 'Identifiant fourni par l\'administration',
        'register.personal_info': 'Informations Personnelles',
        'register.first_name': 'Prénom',
        'register.last_name': 'Nom',
        'register.email': 'Email',
        'register.cin': 'Numéro CIN',
        'register.phone': 'Téléphone',
        'register.address': 'Adresse',
        'register.gender': 'Genre',
        'register.male': 'Homme',
        'register.female': 'Femme',
        'register.academic_info': 'Informations Académiques',
        'register.field_of_study': 'Filière',
        'register.bac_type': 'Type de Baccalauréat',
        'register.scholarship': 'Boursier',
        'register.department': 'Département',
        'register.account_info': 'Informations du Compte',
        'register.username': "Nom d'utilisateur",
        'register.password': 'Mot de passe',
        'register.confirm_password': 'Confirmer le mot de passe',
        'register.accept_terms': 'J\'accepte les conditions d\'utilisation',
        'register.btn': "S'inscrire",
        'register.error_match': 'Les mots de passe ne correspondent pas',
        'register.error_length': 'Le mot de passe doit contenir au moins 6 caractères',
        'register.success': 'Compte créé avec succès ! Redirection...',
        'register.error_used': 'Username ou email déjà utilisé',
        'register.already_account': 'Déjà un compte ?',
        'register.login': 'Se connecter',
        'register.yes': 'Oui',
        'register.no': 'Non',

        // ─── Admin ───
        'admin.chat_btn': 'Chat',
        'admin.tab_stats': 'Statistiques',
        'admin.tab_users': 'Utilisateurs',
        'admin.tab_messages': 'Conversations',
        'admin.tab_docs': 'Documents',
        'admin.tab_notes': 'Notes',
        'admin.tab_identity': 'Identifiants',
        'admin.stat_users': 'Utilisateurs',
        'admin.stat_messages': 'Messages',
        'admin.stat_docs': 'Documents',
        'admin.stat_students': 'Étudiants',
        'admin.stat_professors': 'Professeurs',
        'admin.stat_admins': 'Admins',
        'admin.title_users': 'Liste des utilisateurs',
        'admin.title_messages': 'Historique des conversations',
        'admin.title_docs': 'Documents générés',
        'admin.title_notes': 'Notes des étudiants',
        'admin.title_identity': 'Générer un identifiant',
        'admin.th_id': 'ID',
        'admin.th_username': "Nom d'utilisateur",
        'admin.th_email': 'Email',
        'admin.th_role': 'Rôle',
        'admin.th_date': 'Date',
        'admin.th_action': 'Action',
        'admin.th_user': 'Utilisateur',
        'admin.th_message': 'Message',
        'admin.th_response': 'Réponse',
        'admin.th_intent': 'Intention',
        'admin.th_lang': 'Langue',
        'admin.th_type': 'Type',
        'admin.th_name': 'Nom',
        'admin.th_format': 'Format',
        'admin.th_status': 'Statut',
        'admin.btn_delete': 'Supprimer',
        'admin.btn_generate': 'Générer',
        'admin.btn_copy': 'Copier',
        'admin.fill_all': 'Veuillez remplir tous les champs.',

        // ─── Chat ───
        'chat.placeholder': 'Posez votre question à FASTO...',
        'chat.welcome_title': "Comment puis-je vous aider aujourd'hui ?",
        'chat.welcome_desc': 'Je peux vous renseigner sur le calendrier académique, générer des documents administratifs ou consulter vos notes.',
        'chat.welcome': 'Bonjour ! Je suis votre assistant administratif intelligent.',
        'chat.attach': '📎',
        'chat.new_assistant': 'Nouvel Assistant',
        'chat.admin_section': 'Administration',
        'chat.dashboard': 'Tableau de bord',
        'chat.faculty_mgmt': 'Gestion Faculté',
        'chat.rooms_mgmt': 'Gestion Salles',
        'chat.subjects_mgmt': 'Gestion Matières',
        'chat.planning': 'Planning',
        'chat.prof_section': 'Espace Professeur',
        'chat.my_planning': 'Mon Planning',
        'chat.my_subjects': 'Mes Matières',
        'chat.documents': 'Documents',
        'chat.student_section': 'Espace Étudiant',
        'chat.timetable': 'Emploi du temps',
        'chat.my_documents': 'Mes Documents',
        'chat.recent': 'Récent',
        'chat.assistant_title': 'Assistant FASTO',
        'chat.assistant_subtitle': 'Intelligence Artificielle de la Faculté',
        'chat.sources': 'Sources :',
        'chat.copy': 'Copier',
        'chat.fasto_ai': 'FASTO AI',

        // ─── Quick suggestions ───
        'suggestion.timetable': '📅 Mon emploi du temps',
        'suggestion.certificate': '📄 Attestation de scolarité',
        'suggestion.grades': '📊 Mon relevé de notes',
        'suggestion.scholarships': '🏅 Bourses disponibles',
        'suggestion.programs': '🎓 Filières proposées',
        'suggestion.registration': '📝 Comment s\'inscrire',
        'suggestion.calendar': '📅 Calendrier académique',
        'suggestion.rules': '📜 Règlement intérieur',

        // ─── Document Panel ───
        'form.title': '📄 Générateur de Documents',
        'form.type': 'Type de document',
        'form.name': 'Nom Complet',
        'form.name_placeholder': 'Ex: Ahmed Ben Salah',
        'form.format': 'Format',
        'form.generate': '✨ Générer le document',
        'form.generating': 'Génération en cours...',
        'form.cancel': 'Annuler',
        'form.academic_year': 'Année Universitaire',
        'form.address': 'Adresse Complète',
        'form.company': 'Entreprise de stage',
        'form.duration': 'Durée du stage',
        'form.recipient': 'Destinataire / Objet',
        'form.additional': 'Informations supplémentaires',
        'form.additional_placeholder': 'Ajoutez des précisions si nécessaire...',
        'doc.attest_travail': 'Attestation de travail',
        'doc.attest_scolarite': 'Attestation de scolarité',
        'doc.attest_residence': 'Attestation de résidence',
        'doc.generated': '✅ Votre document a été généré ! Cliquez pour télécharger.',
        'doc.download': '📥 Télécharger le document',
        'doc.error': 'Erreur lors de la génération du document.',
        'doc.name_required': 'Veuillez entrer votre nom complet',
        'doc.certificat_scolarite': 'Certificat de scolarité',
        'doc.releve_notes': 'Relevé de notes',
        'doc.attest_stage': 'Attestation de stage',
        'doc.attest_presence': 'Attestation de présence',
        'doc.attest_residence_label': 'Attestation de résidence',
        'doc.copie_conforme': 'Copie conforme',
        'doc.declaration_honneur': "Déclaration sur l'honneur",
        'doc.lettre_motivation': 'Lettre de motivation',
        'doc.lettre_demande': 'Lettre de demande',
        'doc.lettre_reclamation': 'Lettre de réclamation',
        'doc.group_academic': '📜 Académique',
        'doc.group_admin': '📁 Administratif',
        'doc.group_letters': '✉️ Lettres',

        // ─── Roles ───
        'role.admin': 'Administrateur',
        'role.professor': 'Professeur',
        'role.student': 'Étudiant',

        // ─── Page titles ───
        'page.admin': 'Tableau de Bord Admin',
        'page.chat': 'Assistant IA',
        'page.login': 'Connexion',
        'page.register': 'Inscription',
        'page.default': 'Portail FASTO',
      },

      // ═══════════════════════════════════════════════
      // ENGLISH
      // ═══════════════════════════════════════════════
      en: {
        // ─── Header ───
        'app.title': 'Administrative Assistant',
        'app.subtitle': 'Administrative Portal',
        'app.status': 'Online',
        'app.admin': 'Dashboard',
        'app.logout': 'Sign Out',
        'app.newchat': 'New conversation',
        'app.history': 'Recent conversations',
        'app.noconv': 'No conversations',
        'app.admin_role': 'Administrator',
        'app.user_role': 'User',
        'app.profile': 'My Profile',
        'app.settings': 'Settings',
        'app.language': 'Language',

        // ─── Login ───
        'login.title': 'Sign in to your account',
        'login.subtitle': 'Intelligent Administrative Portal',
        'login.username': 'Username',
        'login.username_placeholder': 'your_username',
        'login.password': 'Password',
        'login.forgot': 'Forgot?',
        'login.remember': 'Remember me',
        'login.btn': 'Sign In',
        'login.error': 'Incorrect username or password',
        'login.empty_fields': 'Please fill in all fields',
        'login.no_account': 'Not a member yet?',
        'login.register': 'Create an account',
        'login.or': 'OR',
        'login.footer': '© 2026 Faculty of Sciences — PFE Project FASTO',

        // ─── Register ───
        'register.title': 'Create a new account',
        'register.choose_role': 'Choose your role',
        'register.student': 'Student',
        'register.professor': 'Professor',
        'register.student_id': 'Student ID',
        'register.prof_id': 'Professor ID',
        'register.id_placeholder': 'ID provided by administration',
        'register.personal_info': 'Personal Information',
        'register.first_name': 'First Name',
        'register.last_name': 'Last Name',
        'register.email': 'Email',
        'register.cin': 'National ID Number',
        'register.phone': 'Phone',
        'register.address': 'Address',
        'register.gender': 'Gender',
        'register.male': 'Male',
        'register.female': 'Female',
        'register.academic_info': 'Academic Information',
        'register.field_of_study': 'Field of Study',
        'register.bac_type': 'High School Diploma Type',
        'register.scholarship': 'Scholarship Holder',
        'register.department': 'Department',
        'register.account_info': 'Account Information',
        'register.username': 'Username',
        'register.password': 'Password',
        'register.confirm_password': 'Confirm Password',
        'register.accept_terms': 'I accept the terms of use',
        'register.btn': 'Sign Up',
        'register.error_match': 'Passwords do not match',
        'register.error_length': 'Password must be at least 6 characters',
        'register.success': 'Account created successfully! Redirecting...',
        'register.error_used': 'Username or email already in use',
        'register.already_account': 'Already have an account?',
        'register.login': 'Sign In',
        'register.yes': 'Yes',
        'register.no': 'No',

        // ─── Admin ───
        'admin.chat_btn': 'Chat',
        'admin.tab_stats': 'Statistics',
        'admin.tab_users': 'Users',
        'admin.tab_messages': 'Conversations',
        'admin.tab_docs': 'Documents',
        'admin.tab_notes': 'Grades',
        'admin.tab_identity': 'Identifiers',
        'admin.stat_users': 'Users',
        'admin.stat_messages': 'Messages',
        'admin.stat_docs': 'Documents',
        'admin.stat_students': 'Students',
        'admin.stat_professors': 'Professors',
        'admin.stat_admins': 'Admins',
        'admin.title_users': 'User List',
        'admin.title_messages': 'Conversation History',
        'admin.title_docs': 'Generated Documents',
        'admin.title_notes': 'Student Grades',
        'admin.title_identity': 'Generate Identifier',
        'admin.th_id': 'ID',
        'admin.th_username': 'Username',
        'admin.th_email': 'Email',
        'admin.th_role': 'Role',
        'admin.th_date': 'Date',
        'admin.th_action': 'Action',
        'admin.th_user': 'User',
        'admin.th_message': 'Message',
        'admin.th_response': 'Response',
        'admin.th_intent': 'Intent',
        'admin.th_lang': 'Language',
        'admin.th_type': 'Type',
        'admin.th_name': 'Name',
        'admin.th_format': 'Format',
        'admin.th_status': 'Status',
        'admin.btn_delete': 'Delete',
        'admin.btn_generate': 'Generate',
        'admin.btn_copy': 'Copy',
        'admin.fill_all': 'Please fill in all fields.',

        // ─── Chat ───
        'chat.placeholder': 'Ask FASTO your question...',
        'chat.welcome_title': 'How can I help you today?',
        'chat.welcome_desc': 'I can help you with the academic calendar, generate administrative documents, or check your grades.',
        'chat.welcome': 'Hello! I am your intelligent administrative assistant.',
        'chat.attach': '📎',
        'chat.new_assistant': 'New Assistant',
        'chat.admin_section': 'Administration',
        'chat.dashboard': 'Dashboard',
        'chat.faculty_mgmt': 'Faculty Management',
        'chat.rooms_mgmt': 'Room Management',
        'chat.subjects_mgmt': 'Subject Management',
        'chat.planning': 'Schedule',
        'chat.prof_section': 'Professor Area',
        'chat.my_planning': 'My Schedule',
        'chat.my_subjects': 'My Subjects',
        'chat.documents': 'Documents',
        'chat.student_section': 'Student Area',
        'chat.timetable': 'Timetable',
        'chat.my_documents': 'My Documents',
        'chat.recent': 'Recent',
        'chat.assistant_title': 'FASTO Assistant',
        'chat.assistant_subtitle': 'Faculty Artificial Intelligence',
        'chat.sources': 'Sources:',
        'chat.copy': 'Copy',
        'chat.fasto_ai': 'FASTO AI',

        // ─── Quick suggestions ───
        'suggestion.timetable': '📅 My timetable',
        'suggestion.certificate': '📄 School certificate',
        'suggestion.grades': '📊 My transcript',
        'suggestion.scholarships': '🏅 Available scholarships',
        'suggestion.programs': '🎓 Available programs',
        'suggestion.registration': '📝 How to register',
        'suggestion.calendar': '📅 Academic calendar',
        'suggestion.rules': '📜 Internal regulations',

        // ─── Document Panel ───
        'form.title': '📄 Document Generator',
        'form.type': 'Document Type',
        'form.name': 'Full Name',
        'form.name_placeholder': 'e.g: John Smith',
        'form.format': 'Format',
        'form.generate': '✨ Generate Document',
        'form.generating': 'Generating...',
        'form.cancel': 'Cancel',
        'form.academic_year': 'Academic Year',
        'form.address': 'Full Address',
        'form.company': 'Internship Company',
        'form.duration': 'Internship Duration',
        'form.recipient': 'Recipient / Subject',
        'form.additional': 'Additional Information',
        'form.additional_placeholder': 'Add details if necessary...',
        'doc.attest_travail': 'Work Certificate',
        'doc.attest_scolarite': 'School Certificate',
        'doc.attest_residence': 'Residence Certificate',
        'doc.generated': '✅ Your document has been generated! Click to download.',
        'doc.download': '📥 Download Document',
        'doc.error': 'Error generating the document.',
        'doc.name_required': 'Please enter your full name',
        'doc.certificat_scolarite': 'School Certificate',
        'doc.releve_notes': 'Transcript',
        'doc.attest_stage': 'Internship Certificate',
        'doc.attest_presence': 'Attendance Certificate',
        'doc.attest_residence_label': 'Residence Certificate',
        'doc.copie_conforme': 'Certified Copy',
        'doc.declaration_honneur': 'Sworn Statement',
        'doc.lettre_motivation': 'Cover Letter',
        'doc.lettre_demande': 'Request Letter',
        'doc.lettre_reclamation': 'Complaint Letter',
        'doc.group_academic': '📜 Academic',
        'doc.group_admin': '📁 Administrative',
        'doc.group_letters': '✉️ Letters',

        // ─── Roles ───
        'role.admin': 'Administrator',
        'role.professor': 'Professor',
        'role.student': 'Student',

        // ─── Page titles ───
        'page.admin': 'Admin Dashboard',
        'page.chat': 'AI Assistant',
        'page.login': 'Sign In',
        'page.register': 'Sign Up',
        'page.default': 'FASTO Portal',
      },

      // ═══════════════════════════════════════════════
      // ARABIC
      // ═══════════════════════════════════════════════
      ar: {
        // ─── Header ───
        'app.title': 'المساعد الإداري',
        'app.subtitle': 'البوابة الإدارية',
        'app.status': 'متصل',
        'app.admin': 'لوحة التحكم',
        'app.logout': 'خروج',
        'app.newchat': 'محادثة جديدة',
        'app.history': 'المحادثات الأخيرة',
        'app.noconv': 'لا توجد محادثات',
        'app.admin_role': 'مدير',
        'app.user_role': 'مستخدم',
        'app.profile': 'ملفي الشخصي',
        'app.settings': 'الإعدادات',
        'app.language': 'اللغة',

        // ─── Login ───
        'login.title': 'تسجيل الدخول إلى حسابك',
        'login.subtitle': 'البوابة الإدارية الذكية',
        'login.username': 'اسم المستخدم',
        'login.username_placeholder': 'اسم_المستخدم',
        'login.password': 'كلمة المرور',
        'login.forgot': 'نسيت؟',
        'login.remember': 'تذكرني',
        'login.btn': 'تسجيل الدخول',
        'login.error': 'اسم المستخدم أو كلمة المرور غير صحيحة',
        'login.empty_fields': 'الرجاء تعبئة جميع الحقول',
        'login.no_account': 'ليس لديك حساب بعد؟',
        'login.register': 'إنشاء حساب',
        'login.or': 'أو',
        'login.footer': '© 2026 كلية العلوم — مشروع تخرج FASTO',

        // ─── Register ───
        'register.title': 'إنشاء حساب جديد',
        'register.choose_role': 'اختر دورك',
        'register.student': 'طالب',
        'register.professor': 'أستاذ',
        'register.student_id': 'معرف الطالب',
        'register.prof_id': 'معرف الأستاذ',
        'register.id_placeholder': 'المعرف المقدم من الإدارة',
        'register.personal_info': 'المعلومات الشخصية',
        'register.first_name': 'الاسم',
        'register.last_name': 'اللقب',
        'register.email': 'البريد الإلكتروني',
        'register.cin': 'رقم بطاقة التعريف',
        'register.phone': 'الهاتف',
        'register.address': 'العنوان',
        'register.gender': 'الجنس',
        'register.male': 'ذكر',
        'register.female': 'أنثى',
        'register.academic_info': 'المعلومات الأكاديمية',
        'register.field_of_study': 'التخصص',
        'register.bac_type': 'نوع البكالوريا',
        'register.scholarship': 'منحة',
        'register.department': 'القسم',
        'register.account_info': 'معلومات الحساب',
        'register.username': 'اسم المستخدم',
        'register.password': 'كلمة المرور',
        'register.confirm_password': 'تأكيد كلمة المرور',
        'register.accept_terms': 'أوافق على شروط الاستخدام',
        'register.btn': 'إنشاء حساب',
        'register.error_match': 'كلمات المرور غير متطابقة',
        'register.error_length': 'يجب أن تحتوي كلمة المرور على 6 أحرف على الأقل',
        'register.success': 'تم إنشاء الحساب بنجاح! جاري التوجيه...',
        'register.error_used': 'اسم المستخدم أو البريد الإلكتروني مستخدم بالفعل',
        'register.already_account': 'لديك حساب بالفعل؟',
        'register.login': 'تسجيل الدخول',
        'register.yes': 'نعم',
        'register.no': 'لا',

        // ─── Admin ───
        'admin.chat_btn': 'محادثة',
        'admin.tab_stats': 'إحصائيات',
        'admin.tab_users': 'المستخدمين',
        'admin.tab_messages': 'المحادثات',
        'admin.tab_docs': 'الوثائق',
        'admin.tab_notes': 'النتائج',
        'admin.tab_identity': 'المعرفات',
        'admin.stat_users': 'مستخدمين',
        'admin.stat_messages': 'رسائل',
        'admin.stat_docs': 'وثائق',
        'admin.stat_students': 'طلبة',
        'admin.stat_professors': 'أساتذة',
        'admin.stat_admins': 'مدراء',
        'admin.title_users': 'قائمة المستخدمين',
        'admin.title_messages': 'سجل المحادثات',
        'admin.title_docs': 'الوثائق المنشأة',
        'admin.title_notes': 'نتائج الطلبة',
        'admin.title_identity': 'إنشاء معرف',
        'admin.th_id': 'الرقم',
        'admin.th_username': 'اسم المستخدم',
        'admin.th_email': 'البريد الإلكتروني',
        'admin.th_role': 'الدور',
        'admin.th_date': 'التاريخ',
        'admin.th_action': 'إجراء',
        'admin.th_user': 'المستخدم',
        'admin.th_message': 'الرسالة',
        'admin.th_response': 'الرد',
        'admin.th_intent': 'النية',
        'admin.th_lang': 'اللغة',
        'admin.th_type': 'النوع',
        'admin.th_name': 'الاسم',
        'admin.th_format': 'الصيغة',
        'admin.th_status': 'الحالة',
        'admin.btn_delete': 'حذف',
        'admin.btn_generate': 'إنشاء',
        'admin.btn_copy': 'نسخ',
        'admin.fill_all': 'الرجاء ملء جميع الحقول.',

        // ─── Chat ───
        'chat.placeholder': 'اكتب سؤالك لـ FASTO...',
        'chat.welcome_title': 'كيف يمكنني مساعدتك اليوم؟',
        'chat.welcome_desc': 'يمكنني مساعدتك بالرزنامة الأكاديمية وإنشاء الوثائق الإدارية ومراجعة نتائجك.',
        'chat.welcome': 'مرحباً! أنا مساعدك الإداري الذكي.',
        'chat.attach': '📎',
        'chat.new_assistant': 'مساعد جديد',
        'chat.admin_section': 'الإدارة',
        'chat.dashboard': 'لوحة التحكم',
        'chat.faculty_mgmt': 'إدارة الكلية',
        'chat.rooms_mgmt': 'إدارة القاعات',
        'chat.subjects_mgmt': 'إدارة المواد',
        'chat.planning': 'البرنامج',
        'chat.prof_section': 'فضاء الأستاذ',
        'chat.my_planning': 'برنامجي',
        'chat.my_subjects': 'موادي',
        'chat.documents': 'الوثائق',
        'chat.student_section': 'فضاء الطالب',
        'chat.timetable': 'جدول الحصص',
        'chat.my_documents': 'وثائقي',
        'chat.recent': 'الأخيرة',
        'chat.assistant_title': 'مساعد FASTO',
        'chat.assistant_subtitle': 'الذكاء الاصطناعي للكلية',
        'chat.sources': 'المصادر:',
        'chat.copy': 'نسخ',
        'chat.fasto_ai': 'FASTO AI',

        // ─── Quick suggestions ───
        'suggestion.timetable': '📅 جدول حصصي',
        'suggestion.certificate': '📄 شهادة دراسية',
        'suggestion.grades': '📊 كشف نقاطي',
        'suggestion.scholarships': '🏅 المنح المتاحة',
        'suggestion.programs': '🎓 التخصصات المتاحة',
        'suggestion.registration': '📝 كيفية التسجيل',
        'suggestion.calendar': '📅 الرزنامة الأكاديمية',
        'suggestion.rules': '📜 النظام الداخلي',

        // ─── Document Panel ───
        'form.title': '📄 منشئ الوثائق',
        'form.type': 'نوع الوثيقة',
        'form.name': 'الاسم الكامل',
        'form.name_placeholder': 'مثال: أحمد بن صالح',
        'form.format': 'الصيغة',
        'form.generate': '✨ إنشاء الوثيقة',
        'form.generating': 'جاري الإنشاء...',
        'form.cancel': 'إلغاء',
        'form.academic_year': 'السنة الجامعية',
        'form.address': 'العنوان الكامل',
        'form.company': 'مؤسسة التربص',
        'form.duration': 'مدة التربص',
        'form.recipient': 'المرسل إليه / الموضوع',
        'form.additional': 'معلومات إضافية',
        'form.additional_placeholder': 'أضف تفاصيل إذا لزم الأمر...',
        'doc.attest_travail': 'شهادة عمل',
        'doc.attest_scolarite': 'شهادة دراسية',
        'doc.attest_residence': 'شهادة إقامة',
        'doc.generated': '✅ تم إنشاء وثيقتك! انقر للتحميل.',
        'doc.download': '📥 تحميل الوثيقة',
        'doc.error': 'خطأ في إنشاء الوثيقة.',
        'doc.name_required': 'الرجاء إدخال الاسم الكامل',
        'doc.certificat_scolarite': 'شهادة التمدرس',
        'doc.releve_notes': 'كشف النقاط',
        'doc.attest_stage': 'شهادة التربص',
        'doc.attest_presence': 'شهادة الحضور',
        'doc.attest_residence_label': 'شهادة الإقامة',
        'doc.copie_conforme': 'نسخة مطابقة',
        'doc.declaration_honneur': 'تصريح شرفي',
        'doc.lettre_motivation': 'رسالة التحفيز',
        'doc.lettre_demande': 'رسالة طلب',
        'doc.lettre_reclamation': 'رسالة شكوى',
        'doc.group_academic': '📜 أكاديمي',
        'doc.group_admin': '📁 إداري',
        'doc.group_letters': '✉️ رسائل',

        // ─── Roles ───
        'role.admin': 'مدير',
        'role.professor': 'أستاذ',
        'role.student': 'طالب',

        // ─── Page titles ───
        'page.admin': 'لوحة تحكم المدير',
        'page.chat': 'المساعد الذكي',
        'page.login': 'تسجيل الدخول',
        'page.register': 'إنشاء حساب',
        'page.default': 'بوابة FASTO',
      }
    };

    const lang = this.getLanguage();
    return translations[lang]?.[key] || translations['fr']?.[key] || key;
  }
}